const { test, expect } = require('@playwright/test');
const fs = require('node:fs/promises');

test('create, inspect, translate, learn, publish and change theme', async ({ page }) => {
  const failures = [];
  page.on('pageerror', error => failures.push(error.message));
  await page.goto('/auth/dev');
  await expect(page.getByRole('heading', { name: 'The worktable.' })).toBeVisible();
  await page.getByRole('link', { name: 'New language', exact: true }).click();
  await page.getByLabel('Language name', { exact: true }).fill('Nerath');
  await page.getByLabel('Seed (optional)', { exact: true }).fill('browser-workshop');
  await page.locator('select[name="size"]').selectOption('128');
  await page.getByRole('button', { name: 'Generate language' }).click();
  await page.getByRole('link', { name: 'Open language →' }).click();
  await expect(page.getByRole('heading', { name: 'Nerath', exact: true })).toBeVisible();
  const languagePath = new URL(page.url()).pathname;
  const id = languagePath.split('/').at(-1);
  await fs.mkdir('test-results/screens', { recursive: true });
  await page.screenshot({ path: 'test-results/screens/overview-light.png', fullPage: true });
  await page.getByRole('button', { name: 'Toggle light and dark mode' }).click();
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark');
  await page.screenshot({ path: 'test-results/screens/overview-dark.png', fullPage: true });
  await page.reload();
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark');
  await page.getByRole('link', { name: 'Lexicon', exact: true }).click();
  await page.getByRole('searchbox', { name: 'Search by meaning or word' }).fill('water');
  await page.getByRole('button', { name: 'Search', exact: true }).click();
  await expect(page.locator('.word-inspector .definition')).toContainText('water');
  await expect(page.locator('.word-history')).toBeVisible();
  await page.getByRole('link', { name: 'History', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Contemporary', exact: true })).toBeVisible();
  await page.getByRole('link', { name: 'Translate', exact: true }).click();
  await page.locator('#translate-input').fill('I see the river');
  await page.getByRole('button', { name: 'Translate →', exact: true }).click();
  await expect(page.locator('.translated-text')).not.toBeEmpty();
  await page.locator('#translate-input').fill('I teleport a spaceship');
  await page.getByRole('button', { name: 'Translate →', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('Unsupported');
  const response = await page.request.get(`/api/languages/${id}/export`);
  expect(response.ok()).toBeTruthy();
  const language = await response.json();
  await page.getByRole('link', { name: 'Learn', exact: true }).click();
  await expect(page.locator('.lesson-prompt')).not.toBeEmpty();
  await page.locator('#lesson-answer').fill(language.examples[0].text);
  await page.getByRole('button', { name: 'Check expression' }).click();
  await expect(page.locator('.lesson-feedback.correct')).toBeVisible();
  await page.getByRole('button', { name: 'Publish revision' }).click();
  await expect(page.locator('.language-subtitle .status')).toHaveText('published');
  await page.goto(languagePath);
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.getByRole('heading', { name: 'Nerath', exact: true })).toBeVisible();
  await page.screenshot({ path: 'test-results/screens/mobile-dark.png', fullPage: true });
  const overflows = await page.evaluate(() => document.documentElement.scrollWidth > innerWidth + 1);
  expect(overflows).toBeFalsy();
  await page.getByRole('button', { name: 'Toggle light and dark mode' }).click();
  await page.screenshot({ path: 'test-results/screens/mobile-light.png', fullPage: true });
  expect(failures).toEqual([]);
});

test('anonymous pages reveal no private data and API refuses writes', async ({ page, request }) => {
  await page.goto('/');
  await expect(page.getByRole('link', { name: 'Open your workshop' })).toBeVisible();
  const response = await request.get('/api/languages');
  expect(response.status()).toBe(401);
  const create = await request.post('/api/projects', { data: { name: 'Unauthorized' } });
  expect(create.status()).toBe(401);
});
